services:
  app:
    image: ghcr.io/sebatec-eu/python-devcontainer:1
    volumes:
      - ..:/workspaces/meeting-scheduler-mcp:cached,z
    command: sleep infinity
    user: vscode
    userns_mode: keep-id
    depends_on: ["greenmail"]
  greenmail:
    image: docker.io/greenmail/standalone:2.0.1
    ports:
      - "3143:3143"
    environment:
      - GREENMAIL_OPTS=-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled
